config/routes.rb
Rails.application.routes.draw do
  # Route Home
  root to: 'home#index'

  # Route Board
  get 'board', to: 'board#index'

  # Route Settings
  get 'settings', to: 'settings#index'

  # Routes Users
  devise_for :users, :path => 'account', :controllers => { :registrations => :registrations }
  resources :users

  # Routes Clients
  resources :clients

  # Routes Design
  resources :designs

  # Routes Companies
  resources :companies
end

app/models/design.rb
class Design < ApplicationRecord
    belongs_to :company
    belongs_to :client
    belongs_to :user
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_design, only: %i[ show edit update destroy ]

  # GET /designs or /designs.json
  def index
    @designs = Design.where(:company_id => current_user.company_id).order('designs.created_at DESC')
    @clients = Client.where(:company_id => current_user.company_id).order('name')
    #.order('name')

    @design = Design.new
  end

  # GET /designs/1 or /designs/1.json
  def show
  end

  # GET /designs/new
  def new
    @design = Design.new
  end

  # GET /designs/1/edit
  def edit
  end

  # POST /designs or /designs.json
  def create
    @design = Design.new(design_params)
    @design.company_id = current_user.company_id
    @design.client_id = params[:design][:client_id]
    @design.user_id = params[:design][:user_id]
    
    respond_to do |format|
      if @design.save
        format.js
        format.html { redirect_to client_path(@design.client_id), notice: "Design was successfully created." }
        format.json { render :show, status: :created, location: @design }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designs/1 or /designs/1.json
  def update
    respond_to do |format|
      if @design.update(design_params)
        format.html { redirect_to design_url(@design), notice: "Design was successfully updated." }
        format.json { render :show, status: :ok, location: @design }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designs/1 or /designs/1.json
  def destroy
    @design.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to client_path(@design.client_id), notice: "Design was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def design_params
      params.require(:design).permit(:name, :url, :company_id, :client_id, :user_id)
    end
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_design.html.erb
<div class="col-lg-3 mb32 col-card-design">
    <div class="card-design1 has-popin">
        <div class="card-design1__exerg">
            <a class="show" href="<%= design.url  %>" target="_blank">
                <img src="<%= asset_path 'Adobe_XD_CC_icon.svg.png' %>">
            </a>
        </div>
        <div class="card-design1__infos">
            <a class="show" href="<%= design.url  %>" target="_blank">
                <h3><%= design.name %></h3>
            </a>
            <div class="card-design1__client">
                    <a href="<%= client_path(design.client.id) %>">
                    <%= design.client.name %>
                    </a>
            </div>
            <div class="card-design1__metas">
                <div>Ajouté le <%= design.created_at.strftime('%d.%m.%y') %></div>
                <% if design.user %>
                <div>Par <%= design.user.fullname %></div>
                <% end %>
            </div>
            <div class="card-design1__actions">

                <a class="show" href="<%= design.url  %>" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M352 96h64c17.7 0 32 14.3 32 32V384c0 17.7-14.3 32-32 32H352c-17.7 0-32 14.3-32 32s14.3 32 32 32h64c53 0 96-43 96-96V128c0-53-43-96-96-96H352c-17.7 0-32 14.3-32 32s14.3 32 32 32zm-7.5 177.4c4.8-4.5 7.5-10.8 7.5-17.4s-2.7-12.9-7.5-17.4l-144-136c-7-6.6-17.2-8.4-26-4.6s-14.5 12.5-14.5 22v72H32c-17.7 0-32 14.3-32 32v64c0 17.7 14.3 32 32 32H160v72c0 9.6 5.7 18.2 14.5 22s19 2 26-4.6l144-136z"/></svg>
                    Lien
                </a>
                
                <a class="card-design__delete delete popin-trigger">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>
                    Supprimer
                </a>

            </div>
        </div>         

        <!--Popin Card-->
        <div class="popin">
            <span class="popin-close">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path d="M310.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L160 210.7 54.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L114.7 256 9.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L160 301.3 265.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L205.3 256 310.6 150.6z"/></svg>
            </span>
            <div class="popin__inner">
                <div class="popin__content">
                    <div class="popin__reminder">
                        Supprimer <%= design.name %> de <%= design.client.name %>
                    </div>
                    <div class="popin__txt">
                        Êtes-vous sûr ?
                    </div>
                    <%= link_to design, method: :delete, remote: :true, class: 'card-design__delete btn btn--error-solid' do  %>
                        Confirmer
                    <% end %>
                </div>
            </div>
        </div>          
    </div>
</div>

app/views/designs/_form.html.erb
<div class="form form-create-design">
    <div class="form__heading">Nouvelle maquette</div>
    <%= simple_form_for(@design, remote: true, html: { id: :add_design }) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form__fieldset">
            <div class="form__input form__input--full">
            <%= f.input :name, :label => 'Nom', :placeholder => 'Blog Post, Website Page...', required: :true %>
            </div>
        </div>
        <div class="form__fieldset">
            <div class="form__input form__input--full">
            <%= f.input :url, :label => 'Lien', :placeholder => 'https://xd.adobe.com/...', required: :true %>
            </div>
        </div>
        
        <% if request.path.include?('designs') %>
            <% if @clients.length > 0 %>
                <div class="form__fieldset">
                    <div class="form__input form__input--full">
                        <%= f.association :client, as: :select, collection: @clients, :label => "Client associé" %>
                        <div class="form__helper">
                            <a class="form-link-helper" href="/clients?addPanel=true">+ Ajouter un client</a>
                        </div>
                    </div>
                </div>
            <% else %>
                <div class="form__fieldset">
                    <div class="form__input form__input--full">
                        <%= f.association :client, as: :select, collection: @clients, :label => "Client associé", :disabled => true %>
                        <div class="form__helper">
                            <div class="info-msg">Pas de clients enregistrés</div>
                            <a class="form-link-helper" href="/clients?addPanel=true">+ Ajouter un client</a>
                        </div>
                    </div>
                </div>
            <% end %>
        <% else %>
        <%= f.hidden_field :client_id, :value => @client.id %>
        <% end %>
       

        <%= f.hidden_field :company_id, :value => current_user.company_id %>
        <%= f.hidden_field :user_id, :value => current_user.id %>


        <% if @clients.length > 0 %>
        <div class="form__actions">
            <%= f.button :submit, :value => 'Ajouter' %>
        </div>   
        <% end %>
    <% end %>
</div>

app/views/designs/create.js.erb
$('#renderDesigns').prepend('<%= j render @design %>');
$('.panel').removeClass('slided');
$('#add_design').trigger("reset");

if ($('.no-designs').length) {
    $('.no-designs').remove()
}
showUserMessage("La maquette a bien été ajoutée")

app/views/designs/destroy.js.erb
$('.card-design__delete').bind('ajax:success', function() {
	$('.popin').removeClass('displayed');
	$(this).parents('.col-card-design').fadeOut();
});

app/views/designs/edit.html.erb
<h1>Editing Design</h1>

<%= render 'form', design: @design %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<%# User Interaction Messages %>
<%# Create User success %>
<div class="user-message"></div>

<section class="sec-layout sec-clients-index">
    <div class="container">
        <div class="row mb40">
            <div class="col-12">
                <div class="breadcrumbs">
                    <ul>
                        <li>
                            <a href="<%= board_path %>">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M41.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l192 192c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.3 256 278.6 86.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-192 192z"/></svg>
                                Tableau de bord
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-8">
                <h1>Maquettes</h1>
            </div>
            <div class="col-4">
                <div class="txt-align-right">
                    <a class="btn-add js-show-panel" data-target="add-design">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z"/></svg>
                        Nouvelle maquette
                    </a>
                </div>
            </div>
            <div class="col-12">
                <div class="action-bar mt16">
                    <!--Search by name action-->
                    <div class="action-bar__item">
                        <div class="sa-chosen-search">
                            <select id="searchDesign">
                                <option></option>
                                <% @designs.each do |design| %>
                                <option value="<%= design.url  %>"><%= design.name %></option>
                                <% end %>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row" id="renderDesigns">
            <%= render @designs %>
        </div>
    </div>

    <% if @designs.length == 0 %>
    <div class="container no-designs">
        <div class="row">
            <div class="col-12">
                <span class="info-msg">Pas de maquettes ajoutées</span>
            </div>
        </div>
    </div>
    <% end %>

    <div class="panel panel-right" data-panel="add-design">
        <div class="panel__overlay"></div>
        <div class="panel__column">
            <div class="panel__close">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path d="M310.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L160 210.7 54.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L114.7 256 9.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L160 301.3 265.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L205.3 256 310.6 150.6z"/></svg>
            </div>
            <div class="panel-column__inner">
                <%= render 'form', design: @design %>
            </div>
        </div>
    </div>

</section>

app/views/designs/new.html.erb
<h1>New Design</h1>

<%= render 'form', design: @design %>

<%= link_to 'Back', designs_path %>

app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @design.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @design.url %>
</p>

<%= link_to 'Edit', edit_design_path(@design) %> |
<%= link_to 'Back', designs_path %>