config/routes.rb
Rails.application.routes.draw do
  # Route Home
  root to: 'home#index'

  # Route Board
  get 'board', to: 'board#index'

  # Route Settings
  get 'settings', to: 'settings#index'

  # Routes Users
  devise_for :users, :path => 'account', :controllers => { :registrations => :registrations }
  resources :users

  # Routes Clients
  resources :clients

  # Routes Design
  resources :designs

  # Routes Companies
  resources :companies
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
    before_action :authenticate_user!

    def index 
        @clients = Client.where(:company_id => current_user.company_id)
        @designs = Design.where(:company_id => current_user.company_id).order('designs.created_at DESC')
        @users = User.where(:company_id => current_user.company_id)
    end
end

app/helpers/board_helper.rb
module BoardHelper
end

app/views/board/index.html.erb
<section class="sec-layout sec-board-index">
    <div class="container">
        <div class="row mb40">
            <div class="col-12">
                <h1>Tableau de bord</h1>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">

            <div class="col-12 col-lg-6 mb32">
                <div class="board-info-card">
                    <div class="board-info-card__heading">
                        Maquettes 
                    </div>
                    <div class="board-info-card__infos">
                        <ul class="list-infos">
                            <% @designs.each do |design| %>
                                <li>
                                    <a href="<%= design.url %>" target="_blank">
                                        <%= design.name %> <span><%= design.client.name %></span>
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path d="M288 32c-80.8 0-145.5 36.8-192.6 80.6C48.6 156 17.3 208 2.5 243.7c-3.3 7.9-3.3 16.7 0 24.6C17.3 304 48.6 356 95.4 399.4C142.5 443.2 207.2 480 288 480s145.5-36.8 192.6-80.6c46.8-43.5 78.1-95.4 93-131.1c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C433.5 68.8 368.8 32 288 32zM432 256c0 79.5-64.5 144-144 144s-144-64.5-144-144s64.5-144 144-144s144 64.5 144 144zM288 192c0 35.3-28.7 64-64 64c-11.5 0-22.3-3-31.6-8.4c-.2 2.8-.4 5.5-.4 8.4c0 53 43 96 96 96s96-43 96-96s-43-96-96-96c-2.8 0-5.6 .1-8.4 .4c5.3 9.3 8.4 20.1 8.4 31.6z"/></svg>
                                    </a>                               
                                </li>
                            <% end %>
                            <% if @designs.length == 0 %>
                            <a class="btn-add btn-add--small" href="/designs?addPanel=true">Ajouter une maquette</a>
                            <% end %>
                        </ul>
                    </div>

                    <div class="board-info-card__actions txt-align-right mt24">
                        <a class="btn2" href="<%= designs_path %>">
                            Toutes les maquettes
                            <span class="btn2__icon">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M342.6 233.4c12.5 12.5 12.5 32.8 0 45.3l-192 192c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3L274.7 256 105.4 86.6c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0l192 192z"/></svg>
                            </span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="col-12 col-lg-6 mb32">
                <div class="board-info-card">
                    <div class="board-info-card__heading">
                        Clients 
                    </div>
                    <div class="board-info-card__infos">
                        <ul class="list-infos">
                            <% @clients.each do |client| %>
                                <li>
                                    <a href="<%= client_path(client.id) %>">
                                        <%= client.name %>
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path d="M288 32c-80.8 0-145.5 36.8-192.6 80.6C48.6 156 17.3 208 2.5 243.7c-3.3 7.9-3.3 16.7 0 24.6C17.3 304 48.6 356 95.4 399.4C142.5 443.2 207.2 480 288 480s145.5-36.8 192.6-80.6c46.8-43.5 78.1-95.4 93-131.1c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C433.5 68.8 368.8 32 288 32zM432 256c0 79.5-64.5 144-144 144s-144-64.5-144-144s64.5-144 144-144s144 64.5 144 144zM288 192c0 35.3-28.7 64-64 64c-11.5 0-22.3-3-31.6-8.4c-.2 2.8-.4 5.5-.4 8.4c0 53 43 96 96 96s96-43 96-96s-43-96-96-96c-2.8 0-5.6 .1-8.4 .4c5.3 9.3 8.4 20.1 8.4 31.6z"/></svg>
                                    </a>                               
                                </li>
                            <% end %>
                            <% if @clients.length == 0 %>
                            <a class="btn-add btn-add--small" href="/clients?addPanel=true">Ajouter un client</a>
                            <% end %>
                        </ul>
                    </div>

                    <div class="board-info-card__actions txt-align-right mt24">
                        <a class="btn2" href="<%= clients_path %>">
                            Tous les clients
                            <span class="btn2__icon">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M342.6 233.4c12.5 12.5 12.5 32.8 0 45.3l-192 192c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3L274.7 256 105.4 86.6c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0l192 192z"/></svg>
                            </span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="col-12 mb32">
                <div class="board-info-card">
                    <div class="board-info-card__heading">
                        Utilisateurs 
                    </div>
                    <div class="board-info-card__infos">
                        <ul class="list-infos">
                            <% @users.each do |user| %>
                                <li>
                                    <a>
                                        <%= user.fullname %>
                                    </a>                               
                                </li>
                            <% end %>
                            <% if @users.length == 0 %>
                            <a class="btn-add btn-add--small" href="<%= settings_path %>">Ajouter un utilisateur</a>
                            <% end %>
                        </ul>
                    </div>

                    <div class="board-info-card__actions txt-align-right mt24">
                        <a class="btn2" href="<%= settings_path %>">
                            Tous les utilisateurs
                            <span class="btn2__icon">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M342.6 233.4c12.5 12.5 12.5 32.8 0 45.3l-192 192c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3L274.7 256 105.4 86.6c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0l192 192z"/></svg>
                            </span>
                        </a>
                    </div>
                </div>
            </div>

            

        </div>
    </div>
</section>