config/routes.rb
Rails.application.routes.draw do
  # Route Home
  root to: 'home#index'

  # Route Board
  get 'board', to: 'board#index'

  # Route Settings
  get 'settings', to: 'settings#index'

  # Routes Users
  devise_for :users, :path => 'account', :controllers => { :registrations => :registrations }
  resources :users

  # Routes Clients
  resources :clients

  # Routes Design
  resources :designs

  # Routes Companies
  resources :companies
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="d-flex justify-content-end">
    <p>Fait avec du ☕️ et beaucoup de ❤️</p>
  </div>
</footer>



<!-- Provisoire -->
<!--
<div style="border-top:6px solid red;margin-bottom:20px;"></div>


<div style="border-bottom:2px solid red;margin-top:20px;"></div>
-->

app/views/layouts/_header.html.erb
<div class="header">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="logo-app">
          <% @logoLink = '' %>
          <% if user_signed_in? %>
            <% @logoLink = board_path %>
          <% else %>
            <% @logoLink = root_path %>
          <% end %>

          <a href="<%== @logoLink %>">
            <span class="logo-app__text"><span class="color-magenta">In</span><span class="color-blue">Dev</span></span>
            <span class="idea-mention">par <img src="https://www.ideagency.fr/hubfs/00_SITE%202022/BRAND%20Assets%202022/favicon-mexico.svg"></span>
          </a>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="header__actions">
        <% if user_signed_in? %>
          <nav>
            <ul>
              <li class="link-item">
                <a href="<%= board_path %>">Tableau de bord</a>
              </li>
              <li class="link-item">
                <a href="<%= designs_path %>">Maquettes</a>
              </li>
              <li class="link-item">
                <a href="<%= clients_path %>">Clients</a>
              </li>
              <li>
                <div class="header__user-actions user-actions">
                  <span class="user-avatar">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0S96 57.3 96 128s57.3 128 128 128zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg>
                  </span>
                  <div class="user-actions__dropdown">
                    <div class="user-actions__item">
                      <a href="<%= edit_user_registration_path %>">Mon compte</a>
                    </div>
                    <div class="user-actions__item">
                      <a href="<%= settings_path %>">Paramètres</a>
                    </div>
                    <div class="user-actions__item">
                      <%= link_to raw('Se déconnecter'), destroy_user_session_path, method: :delete %>
                    </div>
                  </div>
                </div>
              </li>
              <li>
              </li>
              <li>
              </li>
            </ul>
          </nav>
          <% else %>
          <nav>
            <ul>
              <li>
                <a href="<%= new_user_session_path %>">Se connecter</a>
              </li>
              <!--
              <li>
                <a href="<%= new_user_registration_path %>">Créer un compte</a>
              </li>
              -->
            </ul>
          </nav>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InDev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />  

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: '/layouts/header' %>
    <%= yield %>
    <%= render partial: '/layouts/footer' %>
  </body>

</html>